module.exports =    [ { name: 'Carlsberg A',
    symbol: 'CARL-A.CO',
    currency: 'DKK',
    isin: 'DK0010181676',
    sector: 'Consumer Goods' },
{ name: 'Carlsberg B',
    symbol: 'CARL-B.CO',
    currency: 'DKK',
    isin: 'DK0010181759',
    sector: 'Consumer Goods' },
{ name: 'Chr. Hansen Holding',
    symbol: 'CHR.CO',
    currency: 'DKK',
    isin: 'DK0060227585',
    sector: 'Health Care' },
{ name: 'Coloplast B',
    symbol: 'COLO-B.CO',
    currency: 'DKK',
    isin: 'DK0060448595',
    sector: 'Health Care' },
{ name: 'Danske Bank',
    symbol: 'DANSKE.CO',
    currency: 'DKK',
    isin: 'DK0010274414',
    sector: 'Financials' },
{ name: 'DSV',
    symbol: 'DSV.CO',
    currency: 'DKK',
    isin: 'DK0060079531',
    sector: 'Industrials' },
{ name: 'FLSmidth & Co.',
    symbol: 'FLS.CO',
    currency: 'DKK',
    isin: 'DK0010234467',
    sector: 'Industrials' },
{ name: 'G4S plc',
    symbol: 'G4S.CO',
    currency: 'DKK',
    isin: 'GB00B01FLG62',
    sector: 'Industrials' },
{ name: 'Genmab',
    symbol: 'GEN.CO',
    currency: 'DKK',
    isin: 'DK0010272202',
    sector: 'Health Care' },
{ name: 'GN Store Nord',
    symbol: 'GN.CO',
    currency: 'DKK',
    isin: 'DK0010272632',
    sector: 'Health Care' },
{ name: 'ISS',
    symbol: 'ISS.CO',
    currency: 'DKK',
    isin: 'DK0060542181',
    sector: 'Industrials' },
{ name: 'Jyske Bank',
    symbol: 'JYSK.CO',
    currency: 'DKK',
    isin: 'DK0010307958',
    sector: 'Financials' },
{ name: 'Københavns Lufthavne',
    symbol: 'KBHL.CO',
    currency: 'DKK',
    isin: 'DK0010201102',
    sector: 'Industrials' },
{ name: 'Lundbeck',
    symbol: 'LUN.CO',
    currency: 'DKK',
    isin: 'DK0010287234',
    sector: 'Health Care' },
{ name: 'A.P. Møller - Mærsk A',
    symbol: 'MAERSK-A.CO',
    currency: 'DKK',
    isin: 'DK0010244425',
    sector: 'Industrials' },
{ name: 'A.P. Møller - Mærsk B',
    symbol: 'MAERSK-B.CO',
    currency: 'DKK',
    isin: 'DK0010244508',
    sector: 'Industrials' },
{ name: 'Nordea Bank',
    symbol: 'NDA-DKK.CO',
    currency: 'DKK',
    isin: 'SE0000427361',
    sector: 'Financials' },
{ name: 'Novo Nordisk B',
    symbol: 'NOVO-B.CO',
    currency: 'DKK',
    isin: 'DK0060534915',
    sector: 'Health Care' },
{ name: 'Novozymes B',
    symbol: 'NZYM-B.CO',
    currency: 'DKK',
    isin: 'DK0060336014',
    sector: 'Health Care' },
{ name: 'Pandora',
    symbol: 'PNDORA.CO',
    currency: 'DKK',
    isin: 'DK0060252690',
    sector: 'Consumer Goods' },
{ name: 'Rockwool Int. A',
    symbol: 'ROCK-A.CO',
    currency: 'DKK',
    isin: 'DK0010219070',
    sector: 'Industrials' },
{ name: 'Rockwool Int. B',
    symbol: 'ROCK-B.CO',
    currency: 'DKK',
    isin: 'DK0010219153',
    sector: 'Industrials' },
{ name: 'Sydbank',
    symbol: 'SYDB.CO',
    currency: 'DKK',
    isin: 'DK0010311471',
    sector: 'Financials' },
{ name: 'TDC',
    symbol: 'TDC.CO',
    currency: 'DKK',
    isin: 'DK0060228559',
    sector: 'Telecommunications' },
{ name: 'Topdanmark',
    symbol: 'TOP.CO',
    currency: 'DKK',
    isin: 'DK0060477503',
    sector: 'Financials' },
{ name: 'Tryg',
    symbol: 'TRYG.CO',
    currency: 'DKK',
    isin: 'DK0060013274',
    sector: 'Financials' },
{ name: 'Vestas Wind Systems',
    symbol: 'VWS.CO',
    currency: 'DKK',
    isin: 'DK0010268606',
    sector: 'Oil & Gas' },
{ name: 'William Demant Holding',
    symbol: 'WDH.CO',
    currency: 'DKK',
    isin: 'DK0010268440',
    sector: 'Health Care' },
{ name: 'ALK-Abelló B',
    symbol: 'ALK-B.CO',
    currency: 'DKK',
    isin: 'DK0060027142',
    sector: 'Health Care' },
{ name: 'Alm. Brand',
    symbol: 'ALMB.CO',
    currency: 'DKK',
    isin: 'DK0015250344',
    sector: 'Financials' },
{ name: 'Ambu',
    symbol: 'AMBU-B.CO',
    currency: 'DKK',
    isin: 'DK0010303619',
    sector: 'Health Care' },
{ name: 'Auriga Industries B',
    symbol: 'AURI-B.CO',
    currency: 'DKK',
    isin: 'DK0010233816',
    sector: 'Basic Materials' },
{ name: 'Bavarian Nordic',
    symbol: 'BAVA.CO',
    currency: 'DKK',
    isin: 'DK0015998017',
    sector: 'Health Care' },
{ name: 'Bang & Olufsen',
    symbol: 'BO.CO',
    currency: 'DKK',
    isin: 'DK0010218429',
    sector: 'Consumer Goods' },
{ name: 'DFDS',
    symbol: 'DFDS.CO',
    currency: 'DKK',
    isin: 'DK0010259027',
    sector: 'Industrials' },
{ name: 'D/S Norden',
    symbol: 'DNORD.CO',
    currency: 'DKK',
    isin: 'DK0060083210',
    sector: 'Industrials' },
{ name: 'Ø.K.',
    symbol: 'EAC.CO',
    currency: 'DKK',
    isin: 'DK0010006329',
    sector: 'Consumer Goods' },
{ name: 'Greentech Energy Systems',
    symbol: 'GES.CO',
    currency: 'DKK',
    isin: 'DK0010240514',
    sector: 'Utilities' },
{ name: 'IC Group',
    symbol: 'IC.CO',
    currency: 'DKK',
    isin: 'DK0010221803',
    sector: 'Consumer Goods' },
{ name: 'Jeudan',
    symbol: 'JDAN.CO',
    currency: 'DKK',
    isin: 'DK0010171362',
    sector: 'Financials' },
{ name: 'Jutlander Bank',
    symbol: 'JUTBK.CO',
    currency: 'DKK',
    isin: 'DK0060050045',
    sector: 'Financials' },
{ name: 'Matas',
    symbol: 'MATAS.CO',
    currency: 'DKK',
    isin: 'DK0060497295',
    sector: 'Consumer Services' },
{ name: 'NKT Holding',
    symbol: 'NKT.CO',
    currency: 'DKK',
    isin: 'DK0010287663',
    sector: 'Industrials' },
{ name: 'Onxeo',
    symbol: 'ONXEO.CO',
    currency: 'DKK',
    isin: 'FR0010095596',
    sector: 'Health Care' },
{ name: 'Össur',
    symbol: 'OSSR.CO',
    currency: 'DKK',
    isin: 'IS0000000040',
    sector: 'Health Care' },
{ name: 'Royal UNIBREW',
    symbol: 'RBREW.CO',
    currency: 'DKK',
    isin: 'DK0010242999',
    sector: 'Consumer Goods' },
{ name: 'Ringkjøbing Landbobank',
    symbol: 'RILBA.CO',
    currency: 'DKK',
    isin: 'DK0060032068',
    sector: 'Financials' },
{ name: 'SAS',
    symbol: 'SAS-DKK.CO',
    currency: 'DKK',
    isin: 'SE0003366871',
    sector: 'Consumer Services' },
{ name: 'Schouw & Co.',
    symbol: 'SCHO.CO',
    currency: 'DKK',
    isin: 'DK0010253921',
    sector: 'Industrials' },
{ name: 'SimCorp',
    symbol: 'SIM.CO',
    currency: 'DKK',
    isin: 'DK0060495240',
    sector: 'Technology' },
{ name: 'Solar B',
    symbol: 'SOLAR-B.CO',
    currency: 'DKK',
    isin: 'DK0010274844',
    sector: 'Industrials' },
{ name: 'Spar Nord Bank',
    symbol: 'SPNO.CO',
    currency: 'DKK',
    isin: 'DK0060036564',
    sector: 'Financials' },
{ name: 'Tivoli A/S',
    symbol: 'TIV.CO',
    currency: 'DKK',
    isin: 'DK0010040500',
    sector: 'Consumer Services' },
{ name: 'United Int. Enterprises',
    symbol: 'UIE.CO',
    currency: 'DKK',
    isin: 'BSP951331318',
    sector: 'Consumer Goods' },
{ name: 'Zealand Pharma',
    symbol: 'ZEAL.CO',
    currency: 'DKK',
    isin: 'DK0060257814',
    sector: 'Health Care' },
{ name: 'AaB',
    symbol: 'AAB.CO',
    currency: 'DKK',
    isin: 'DK0010247014',
    sector: 'Consumer Services' },
{ name: 'Admiral Capital B',
    symbol: 'ADMCAP-B.CO',
    currency: 'DKK',
    isin: 'DK0060052843',
    sector: 'Financials' },
{ name: 'Andersen & Martini B',
    symbol: 'AM-B.CO',
    currency: 'DKK',
    isin: 'DK0010283597',
    sector: 'Consumer Services' },
{ name: 'Brdr. A & O Johansen præf.',
    symbol: 'AOJ-P.CO',
    currency: 'DKK',
    isin: 'DK0010231018',
    sector: 'Industrials' },
{ name: 'Arkil Holding B',
    symbol: 'ARKIL-B.CO',
    currency: 'DKK',
    isin: 'DK0010025113',
    sector: 'Industrials' },
{ name: 'Atlantic Petroleum',
    symbol: 'ATLA-DKK.CO',
    currency: 'DKK',
    isin: 'FO000A0DN9X4',
    sector: 'Oil & Gas' },
{ name: 'Berlin IV B',
    symbol: 'BERLIV-B.CO',
    currency: 'DKK',
    isin: 'DK0060085694',
    sector: 'Financials' },
{ name: 'Brøndby IF',
    symbol: 'BIF.CO',
    currency: 'DKK',
    isin: 'DK0010247956',
    sector: 'Consumer Services' },
{ name: 'BioPorto',
    symbol: 'BIOPOR.CO',
    currency: 'DKK',
    isin: 'DK0011048619',
    sector: 'Health Care' },
{ name: 'Blue Vision A',
    symbol: 'BLVIS-A.CO',
    currency: 'DKK',
    isin: 'DK0060278737',
    sector: 'Financials' },
{ name: 'BankNordik',
    symbol: 'BNORDIK-CSE.CO',
    currency: 'DKK',
    isin: 'FO0000000088',
    sector: 'Financials' },
{ name: 'BoConcept Holding B',
    symbol: 'BOCON-B.CO',
    currency: 'DKK',
    isin: 'DK0060050201',
    sector: 'Consumer Goods' },
{ name: 'F.E. Bording B',
    symbol: 'BORD-B.CO',
    currency: 'DKK',
    isin: 'DK0010008028',
    sector: 'Industrials' },
{ name: 'CBRAIN',
    symbol: 'CBRAIN.CO',
    currency: 'DKK',
    isin: 'DK0060030286',
    sector: 'Technology' },
{ name: 'ChemoMetec',
    symbol: 'CHEMM.CO',
    currency: 'DKK',
    isin: 'DK0060055861',
    sector: 'Health Care' },
{ name: 'Columbus',
    symbol: 'COLUM.CO',
    currency: 'DKK',
    isin: 'DK0010268366',
    sector: 'Technology' },
{ name: 'Comendo',
    symbol: 'COM.CO',
    currency: 'DKK',
    isin: 'DK0060055515',
    sector: 'Technology' },
{ name: 'Copenhagen Capital',
    symbol: 'CPHCAP.CO',
    currency: 'DKK',
    isin: 'DK0060093607',
    sector: 'Financials' },
{ name: 'Danske Andelskassers Bank',
    symbol: 'DAB.CO',
    currency: 'DKK',
    isin: 'DK0060299063',
    sector: 'Financials' },
{ name: 'Dantax',
    symbol: 'DANT.CO',
    currency: 'DKK',
    isin: 'DK0015205637',
    sector: 'Consumer Goods' },
{ name: 'Dantherm',
    symbol: 'DANTH.CO',
    currency: 'DKK',
    isin: 'DK0010223692',
    sector: 'Industrials' },
{ name: 'Deltaq',
    symbol: 'DELTAQ.CO',
    currency: 'DKK',
    isin: 'DK0060090181',
    sector: 'Financials' },
{ name: 'Djurslands Bank',
    symbol: 'DJUR.CO',
    currency: 'DKK',
    isin: 'DK0060136273',
    sector: 'Financials' },
{ name: 'DLH',
    symbol: 'DLH.CO',
    currency: 'DKK',
    isin: 'DK0060038933',
    sector: 'Industrials' },
{ name: 'Egetæpper B',
    symbol: 'EGE-B.CO',
    currency: 'DKK',
    isin: 'DK0060458206',
    sector: 'Consumer Goods' },
{ name: 'Euroinvestor.com',
    symbol: 'EI.CO',
    currency: 'DKK',
    isin: 'DK0060074656',
    sector: 'Consumer Services' },
{ name: 'Aarhus Elite B',
    symbol: 'ELITE-B.CO',
    currency: 'DKK',
    isin: 'DK0010263722',
    sector: 'Consumer Services' },
{ name: 'Erria',
    symbol: 'ERRIA.CO',
    currency: 'DKK',
    isin: 'DK0060101483',
    sector: 'Industrials' },
{ name: 'Expedit B',
    symbol: 'EXP-B.CO',
    currency: 'DKK',
    isin: 'DK0015312474',
    sector: 'Consumer Goods' },
{ name: 'Exiqon',
    symbol: 'EXQ.CO',
    currency: 'DKK',
    isin: 'DK0060077758',
    sector: 'Health Care' },
{ name: 'Fast Ejendom Danmark',
    symbol: 'FED.CO',
    currency: 'DKK',
    isin: 'DK0060522746',
    sector: 'Financials' },
{ name: 'FirstFarms',
    symbol: 'FFARMS.CO',
    currency: 'DKK',
    isin: 'DK0060056166',
    sector: 'Consumer Goods' },
{ name: 'Flügger B',
    symbol: 'FLUG-B.CO',
    currency: 'DKK',
    isin: 'DK0010218189',
    sector: 'Industrials' },
{ name: 'Fynske Bank',
    symbol: 'FYNBK.CO',
    currency: 'DKK',
    isin: 'DK0060520377',
    sector: 'Financials' },
{ name: 'Gabriel Holding',
    symbol: 'GABR.CO',
    currency: 'DKK',
    isin: 'DK0060124691',
    sector: 'Consumer Goods' },
{ name: 'German High Street Properties',
    symbol: 'GERHSP-B.CO',
    currency: 'DKK',
    isin: 'DK0060093524',
    sector: 'Financials' },
{ name: 'Glunz & Jensen',
    symbol: 'GJ.CO',
    currency: 'DKK',
    isin: 'DK0010249309',
    sector: 'Industrials' },
{ name: 'Grønlandsbanken',
    symbol: 'GRLA.CO',
    currency: 'DKK',
    isin: 'DK0010230630',
    sector: 'Financials' },
{ name: 'Gyldendal A',
    symbol: 'GYLD-A.CO',
    currency: 'DKK',
    isin: 'DK0010247527',
    sector: 'Consumer Services' },
{ name: 'Gyldendal B',
    symbol: 'GYLD-B.CO',
    currency: 'DKK',
    isin: 'DK0010247600',
    sector: 'Consumer Services' },
{ name: 'Harboes Bryggeri B',
    symbol: 'HARB-B.CO',
    currency: 'DKK',
    isin: 'DK0060014751',
    sector: 'Consumer Goods' },
{ name: 'Brdr.Hartmann',
    symbol: 'HART.CO',
    currency: 'DKK',
    isin: 'DK0010256197',
    sector: 'Industrials' },
{ name: 'H+H International',
    symbol: 'HH.CO',
    currency: 'DKK',
    isin: 'DK0015202451',
    sector: 'Industrials' },
{ name: 'Højgaard Holding A',
    symbol: 'HOEJ-A.CO',
    currency: 'DKK',
    isin: 'DK0010255892',
    sector: 'Industrials' },
{ name: 'Højgaard Holding B',
    symbol: 'HOEJ-B.CO',
    currency: 'DKK',
    isin: 'DK0010255975',
    sector: 'Industrials' },
{ name: 'Hvidbjerg Bank',
    symbol: 'HVID.CO',
    currency: 'DKK',
    isin: 'DK0060135978',
    sector: 'Financials' },
{ name: 'InterMail B',
    symbol: 'IMAIL-B.CO',
    currency: 'DKK',
    isin: 'DK0010212224',
    sector: 'Industrials' },
{ name: 'Jensen & Møller Invest',
    symbol: 'JMI.CO',
    currency: 'DKK',
    isin: 'DK0010020668',
    sector: 'Financials' },
{ name: 'Brd. Klee B',
    symbol: 'KLEE-B.CO',
    currency: 'DKK',
    isin: 'DK0010129089',
    sector: 'Industrials' },
{ name: 'Kreditbanken',
    symbol: 'KRE.CO',
    currency: 'DKK',
    isin: 'DK0010253764',
    sector: 'Financials' },
{ name: 'Lån og Spar Bank',
    symbol: 'LASP.CO',
    currency: 'DKK',
    isin: 'DK0010201532',
    sector: 'Financials' },
{ name: 'Land & Leisure A',
    symbol: 'LL-A.CO',
    currency: 'DKK',
    isin: 'DK0010243534',
    sector: 'Consumer Services' },
{ name: 'Land & Leisure B',
    symbol: 'LL-B.CO',
    currency: 'DKK',
    isin: 'DK0010240860',
    sector: 'Consumer Services' },
{ name: 'Lollands Bank',
    symbol: 'LOLB.CO',
    currency: 'DKK',
    isin: 'DK0060000107',
    sector: 'Financials' },
{ name: 'Luxor B',
    symbol: 'LUXOR-B.CO',
    currency: 'DKK',
    isin: 'DK0010213628',
    sector: 'Financials' },
{ name: 'Migatronic B',
    symbol: 'MIGA-B.CO',
    currency: 'DKK',
    isin: 'DK0010225127',
    sector: 'Industrials' },
{ name: 'Møns Bank',
    symbol: 'MNBA.CO',
    currency: 'DKK',
    isin: 'DK0060133841',
    sector: 'Financials' },
{ name: 'Mols-Linien',
    symbol: 'MOLS.CO',
    currency: 'DKK',
    isin: 'DK0060135465',
    sector: 'Consumer Services' },
{ name: 'Monb.& Thor. B',
    symbol: 'MT-B.CO',
    currency: 'DKK',
    isin: 'DK0010224310',
    sector: 'Industrials' },
{ name: 'NeuroSearch',
    symbol: 'NEUR.CO',
    currency: 'DKK',
    isin: 'DK0010224666',
    sector: 'Health Care' },
{ name: 'Newcap Holding',
    symbol: 'NEWCAP.CO',
    currency: 'DKK',
    isin: 'DK0010212570',
    sector: 'Financials' },
{ name: 'Nordic Shipholding',
    symbol: 'NORDIC.CO',
    currency: 'DKK',
    isin: 'DK0060083996',
    sector: 'Oil & Gas' },
{ name: 'Nordjyske Bank',
    symbol: 'NORDJB.CO',
    currency: 'DKK',
    isin: 'DK0060034353',
    sector: 'Financials' },
{ name: 'North Media',
    symbol: 'NORTHM.CO',
    currency: 'DKK',
    isin: 'DK0010270347',
    sector: 'Consumer Services' },
{ name: 'Nordicom',
    symbol: 'NRDC.CO',
    currency: 'DKK',
    isin: 'DK0010158500',
    sector: 'Financials' },
{ name: 'Nordfyns Bank',
    symbol: 'NRDF.CO',
    currency: 'DKK',
    isin: 'DK0010015072',
    sector: 'Financials' },
{ name: 'Nørresundby Bank',
    symbol: 'NRSU.CO',
    currency: 'DKK',
    isin: 'DK0060135549',
    sector: 'Financials' },
{ name: 'NTR Holding B',
    symbol: 'NTR-B.CO',
    currency: 'DKK',
    isin: 'DK0010027671',
    sector: 'Industrials' },
{ name: 'NunaMinerals',
    symbol: 'NUNA.CO',
    currency: 'DKK',
    isin: 'DK0060492577',
    sector: 'Basic Materials' },
{ name: 'Østjydsk Bank',
    symbol: 'OJBA.CO',
    currency: 'DKK',
    isin: 'DK0010017607',
    sector: 'Financials' },
{ name: 'Per Aarsleff B',
    symbol: 'PAAL-B.CO',
    currency: 'DKK',
    isin: 'DK0010243450',
    sector: 'Industrials' },
{ name: 'PARKEN Sport & Entertainment',
    symbol: 'PARKEN.CO',
    currency: 'DKK',
    isin: 'DK0010237643',
    sector: 'Consumer Services' },
{ name: 'Prime Office',
    symbol: 'PRIMOF.CO',
    currency: 'DKK',
    isin: 'DK0060137594',
    sector: 'Financials' },
{ name: 'Roblon B',
    symbol: 'RBLN-B.CO',
    currency: 'DKK',
    isin: 'DK0060485019',
    sector: 'Industrials' },
{ name: 'Realia',
    symbol: 'REALIA.CO',
    currency: 'DKK',
    isin: 'DK0010131309',
    sector: 'Financials' },
{ name: 'Rella Holding',
    symbol: 'RELLA.CO',
    currency: 'DKK',
    isin: 'DK0016033889',
    sector: 'Financials' },
{ name: 'Rias B',
    symbol: 'RIAS-B.CO',
    currency: 'DKK',
    isin: 'DK0010125848',
    sector: 'Industrials' },
{ name: 'SSBV-Rovsing',
    symbol: 'ROV.CO',
    currency: 'DKK',
    isin: 'DK0060400398',
    sector: 'Industrials' },
{ name: 'RTX',
    symbol: 'RTX.CO',
    currency: 'DKK',
    isin: 'DK0010267129',
    sector: 'Technology' },
{ name: 'Salling Bank',
    symbol: 'SALB.CO',
    currency: 'DKK',
    isin: 'DK0010017367',
    sector: 'Financials' },
{ name: 'Sanistål',
    symbol: 'SANI.CO',
    currency: 'DKK',
    isin: 'DK0010245661',
    sector: 'Consumer Services' },
{ name: 'Scandinavian Brake Systems',
    symbol: 'SBS.CO',
    currency: 'DKK',
    isin: 'DK0060042612',
    sector: 'Consumer Goods' },
{ name: 'Small Cap Danmark',
    symbol: 'SCD.CO',
    currency: 'DKK',
    isin: 'DK0010305077',
    sector: 'Financials' },
{ name: 'Silkeborg IF Invest B',
    symbol: 'SIF-B.CO',
    currency: 'DKK',
    isin: 'DK0010128008',
    sector: 'Consumer Services' },
{ name: 'SKAKO',
    symbol: 'SKAKO.CO',
    currency: 'DKK',
    isin: 'DK0010231877',
    sector: 'Industrials' },
{ name: 'Skjern Bank',
    symbol: 'SKJE.CO',
    currency: 'DKK',
    isin: 'DK0010295922',
    sector: 'Financials' },
{ name: 'Scandinavian Private Equity',
    symbol: 'SPEAS.CO',
    currency: 'DKK',
    isin: 'DK0060068682',
    sector: 'Financials' },
{ name: 'SP Group',
    symbol: 'SPG.CO',
    currency: 'DKK',
    isin: 'DK0010244771',
    sector: 'Basic Materials' },
{ name: 'Strategic Investments',
    symbol: 'STRINV.CO',
    currency: 'DKK',
    isin: 'DK0010271238',
    sector: 'Financials' },
{ name: 'STYLEPIT',
    symbol: 'STYLE.CO',
    currency: 'DKK',
    isin: 'DK0060046522',
    sector: 'Consumer Services' },
{ name: 'TK Development',
    symbol: 'TKDV.CO',
    currency: 'DKK',
    isin: 'DK0010258995',
    sector: 'Financials' },
{ name: 'TORM',
    symbol: 'TORM.CO',
    currency: 'DKK',
    isin: 'DK0060082915',
    sector: 'Industrials' },
{ name: 'Totalbanken',
    symbol: 'TOTA.CO',
    currency: 'DKK',
    isin: 'DK0060082758',
    sector: 'Financials' },
{ name: 'Topsil Semiconductor Materials',
    symbol: 'TPSL.CO',
    currency: 'DKK',
    isin: 'DK0010271584',
    sector: 'Technology' },
{ name: 'Veloxis Pharmaceuticals',
    symbol: 'VELO.CO',
    currency: 'DKK',
    isin: 'DK0060048148',
    sector: 'Health Care' },
{ name: 'Viborg Håndbold Klub',
    symbol: 'VIBHK.CO',
    currency: 'DKK',
    isin: 'DK0016017171',
    sector: 'Consumer Services' },
{ name: 'Victor International',
    symbol: 'VIINT.CO',
    currency: 'DKK',
    isin: 'DK0010022367',
    sector: 'Financials' },
{ name: 'Victoria Properties',
    symbol: 'VIPRO.CO',
    currency: 'DKK',
    isin: 'DK0015216675',
    sector: 'Financials' },
{ name: 'Vestjysk Bank',
    symbol: 'VJBA.CO',
    currency: 'DKK',
    isin: 'DK0010304500',
    sector: 'Financials' } ];

